DB構築
taichees/src_py pull request #2
Opened 2024-10-31 03:52 UTC by malfoy33

users、contentsテーブル作成のためのmodelsファイルを作成しました。

2024-10-31 05:03 UTC, taichees requested changes

2024-10-31 05:03 UTC, taichees commented on polls/models/Contents.py
設計資料と整合性がありません。
dataではなくdateでは？
あと、dateであればtimestamp型が良いかと思います。
その他で設計書側を直すべきところとして、contentsになっているところをcontentへ直しておいて欲しいです

2024-11-01 13:23 UTC, malfoy33 commented
contentsテーブルのカラム変更を行いました。
・contentsIdからcontentIdに名称変更
・dataからdateに名称変更
・dateの型をTEXTからDateTime型に変更

2024-11-01 23:57 UTC, taichees approved these changes
OKです！

2024-11-01 23:57 UTC, merged